-- MySQL Script generated by MySQL Workbench
-- Thu Aug 10 11:15:52 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- Esta es la base de datos  terminada que contiene todas las tablas y relaciones. 
-- 
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
--
-- Esta es la base de datos  terminada que contiene todas las tablas y relaciones. 
-- 
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`School`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`schools` (
  `id_school` INT NOT NULL AUTO_INCREMENT,
  `name_school` VARCHAR(50) NOT NULL,
  `address` VARCHAR(50) NOT NULL,
  `phone` VARCHAR(50) NOT NULL,
  `mission` VARCHAR(700) NOT NULL,
  `vision` VARCHAR(700) NOT NULL,
  `about_us` VARCHAR(700) NOT NULL,
  `info_school` VARCHAR(1000) NOT NULL,
   `estrato` VARCHAR(10),
`status`  VARCHAR(10),
  PRIMARY KEY (`id_school`),
  UNIQUE INDEX `id_school_UNIQUE` (`id_school` ASC) VISIBLE)
ENGINE = InnoDB;
-- -----------------------------------------------------
-- Table `mydb`.`user_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user_types` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;
-- -----------------------------------------------------
-- Table `mydb`.`guardians`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`guardians` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(50) NOT NULL,
  `residensial_address` VARCHAR(45) NOT NULL,
  `relacion` VARCHAR(45) NOT NULL,
  `document_type` VARCHAR(3) NOT NULL,
  `document_number` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `profile` VARCHAR(100) NOT NULL,
  `status` VARCHAR(1) NOT NULL,
  `registration_year` INT NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `residential_address` VARCHAR(45) NOT NULL,
  `document_type` VARCHAR(4) NOT NULL,
  `document_number` VARCHAR(45) NOT NULL,
  `school_id` INT NOT NULL,
  `usertype_id` INT NOT NULL,
  `guardians_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_user_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `password_UNIQUE` (`profile` ASC) VISIBLE,
  INDEX `fk_user_school_idx` (`school_id` ASC) VISIBLE,
  INDEX `fk_user_user_type_idx` (`usertype_id` ASC) VISIBLE,
  INDEX `fk_user_parents_idx` (`parents_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_school`
    FOREIGN KEY (`school_id`)
    REFERENCES `mydb`.`schools` (`id_school`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_user_type`
    FOREIGN KEY (`usertype_id`)
    REFERENCES `mydb`.`user_types` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_parents`
    FOREIGN KEY (`guardians_id`)
    REFERENCES `mydb`.`guardians` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`subjects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`subjects` (
  `id` INT NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_subject_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`courses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`courses` (
  `id` INT NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  `capacity` INT NOT NULL,
  `subject_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_grades_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_courses_subjets_id` (`subject_id` ASC) VISIBLE,
  CONSTRAINT `fk_courses_subjets`
    FOREIGN KEY (`subject_id`)
    REFERENCES `mydb`.`subjects` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`subjects_has_degree`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`subjects_has_degree` (
  `id_subject` INT NOT NULL,
  `id_grades` INT NOT NULL,
  `date` DATE NOT NULL,
  `hours` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_subject`, `id_grades`),
  INDEX `fk_subjects_has_degree_id_grades` (`id_grades` ASC) VISIBLE,
  INDEX `fk_subjects_has_degree_id_subject` (`id_subject` ASC) VISIBLE,
  CONSTRAINT `fk_subjects_has_degree_subjects`
    FOREIGN KEY (`id_subject`)
    REFERENCES `mydb`.`subjects` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_subjects_has_degree`
    FOREIGN KEY (`id_grades`)
    REFERENCES `mydb`.`courses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`subjects_has_grades-notas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`subjects_has_grades-notes` (
  `id_subject` INT NOT NULL,
  `id_grades` INT NOT NULL,
  PRIMARY KEY (`id_subject`, `id_grades`),
  INDEX `fk_subjects_has_grades-notas_subjects_id` (`id_subject` ASC) VISIBLE,
  CONSTRAINT `fk_subjects_has_grades-notas_subjects`
    FOREIGN KEY (`id_subject`)
    REFERENCES `mydb`.`subjects` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
-- -----------------------------------------------------
-- Table `mydb`.`subjects_Degree`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`subjects_degree` (
  `date` DATE NOT NULL,
  `id_subject` INT NOT NULL,
  `id_grades` INT NOT NULL,
  PRIMARY KEY (`id_subject`, `id_grades`),
  INDEX `fk_subjects_has_degree_id` (`id_grades` ASC) VISIBLE,
  INDEX `fk_subjects_has_degree_subjects_id` (`id_subject` ASC) VISIBLE,
  CONSTRAINT `fk_subjects_has_degree_subjects`
    FOREIGN KEY (`id_subject`)
    REFERENCES `mydb`.`subjects` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_subjects_has_degree`
    FOREIGN KEY (`id_grades`)
    REFERENCES `mydb`.`courses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`quarters`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`quarters` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`notes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`notes` (
  `id` INT NOT NULL,
  `value` DOUBLE NOT NULL,
  `year` INT NOT NULL,
  `subjet_id` INT NOT NULL,
  `quarter_id` INT NOT NULL,
  `course_id` INT NOT NULL,
  `reportedby_id` INT NOT NULL,
  `assignedto_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_grades_subjet_id` (`subjet_id` ASC, `reportedby_id` ASC) VISIBLE,
  INDEX `fk_grades_quarters_id` (`quarter_id` ASC) VISIBLE,
  INDEX `fk_notes_course_id` (`course_id` ASC) VISIBLE,
  INDEX `fk_reportedby_id_id` (`reportedby_id` ASC) VISIBLE,
  INDEX `fk_asignedto_id` (`assignedto_id` ASC) VISIBLE,
  CONSTRAINT `fk_grades_subjet`
    FOREIGN KEY (`subjet_id` , `reportedby_id`)
    REFERENCES `mydb`.`subjects` (`id` , `id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_grades_quarters`
    FOREIGN KEY (`quarter_id`)
    REFERENCES `mydb`.`quarters` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_notes_courses`
    FOREIGN KEY (`course_id`)
    REFERENCES `mydb`.`courses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reportedby_id`
    FOREIGN KEY (`reportedby_id`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_asignedto_id`
    FOREIGN KEY (`assignedto_id`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tasks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tasks` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `description` TEXT(500) NOT NULL,
  `user_id` INT NOT NULL,
  `course_id` INT NOT NULL,
  `subjet_id` INT NOT NULL,
  PRIMARY KEY (`id`, `description`),
  INDEX `fk_tasks_user_id` (`user_id` ASC) VISIBLE,
  INDEX `fk_tasks_course_id` (`course_id` ASC) VISIBLE,
  INDEX `fk_tasks_subjet_id` (`subjet_id` ASC) VISIBLE,
  CONSTRAINT `fk_tasks_User`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tasks_course`
    FOREIGN KEY (`course_id`)
    REFERENCES `mydb`.`courses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tasks_subjet`
    FOREIGN KEY (`subjet_id`)
    REFERENCES `mydb`.`subjects` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`schedules`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`schedules` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `year` INT NOT NULL,
  `wednesday` TEXT(200) NOT NULL,
  `tuesday` TEXT(200) NOT NULL,
  `monday` TEXT(200) NOT NULL,
  `thursday` TEXT(200) NOT NULL,
  `friday` TEXT(200) NOT NULL,
  `saturday` TEXT(200) NOT NULL,
  `course_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_schedules_course_id` (`course_id` ASC) VISIBLE,
  CONSTRAINT `fk_schedules_course`
    FOREIGN KEY (`course_id`)
    REFERENCES `mydb`.`courses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`registereds`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`registereds` (
  `id` INT NOT NULL,
  `year` INT NOT NULL,
  `user_id` INT NOT NULL,
  `course_id` INT NOT NULL,
  INDEX `fk_registereds_user_id` (`user_id` ASC) VISIBLE,
  INDEX `fk_registereds_course_id` (`course_id` ASC) VISIBLE,
  CONSTRAINT `fk_table_User`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_table_course`
    FOREIGN KEY (`course_id`)
    REFERENCES `mydb`.`courses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;